### ISSUE TITLE
Unable to upload torrents

### ISSUE THREAD

**Issue by kab3lle** [KevinJDurant/OpenTorrentSite#1]
Hello, Please tell me this is still be developed?

My issues is I get this message when trying to upload a .torrent

"There seems to be an error moving your file."

Probably a permission problem?

I'm stuck and don't know what to do. Thanks

**Comment by KevinJDurant** [comment]
Hi @kab3lle

I'm not currently working on it but I think it's because you don't have a torrents folder in your root directory (code is very sloppy). Could you try and make a "torrents" folder in the same folder where the css, plugins, fonts... folder is?

If it still doesn't work then please provide a screenshot of your folder structure.

**Comment by kab3lle** [comment]
Hey, I did try that.

(KevinJDurant: removed screenshot as it had you name in it)

**Comment by KevinJDurant** [comment]
Hmm I'll take a look at it during the weekend, might fix some other stuff that I've been postponing forever. It might be an issue with the php document root variable (i'll change the paths to relative ones), also I've edited your comment as it contained some personal info.

Did you already set the permissions? I never really tried it on any distribution but some might require you to explicitly give PHP or the user who runs the server permissions in your /var/www path.

**Comment by kab3lle** [comment]
Hey thanks for removing the pic I did it in a rush.

Scratch that it was me I managed to get it to upload torrents and move torrent fine now.

**Comment by kab3lle** [comment]
My new issue is after Ive uploaded a .torrent file and try to redownload the .torrent file it tries to redirect to itorrents is it possible to just download the source .torrent file directly?

**Comment by KevinJDurant** [comment]
Hi,

Sorry I didn't really have time last weekend. Due to legal concerns and safety issues I decided not to save the .torrent files on the server, only to save the magnets in the database. 

To remove the download button delete or comment these lines:

- https://github.com/KevinJDurant/OpenTorrentSite/blob/a142dc4a460b46af0d67a4089bed36c60d3591f8/en/view/torrent.php#L242
- https://github.com/KevinJDurant/OpenTorrentSite/blob/a142dc4a460b46af0d67a4089bed36c60d3591f8/en/view/my-torrents.php#L174
- https://github.com/KevinJDurant/OpenTorrentSite/blob/a142dc4a460b46af0d67a4089bed36c60d3591f8/en/view/user-torrents.php#L172
- https://github.com/KevinJDurant/OpenTorrentSite/blob/a142dc4a460b46af0d67a4089bed36c60d3591f8/index.php#L178

If you want to save the .torrents then you'd need to move them to a folder outside your web environment and rename the .torrent to the torrentid. Are you familiar with PHP?

**Comment by kab3lle** [comment]
Hi Kevin,

Yea I'm no developer or anything so wouldn't know where to start with saving the .torrents locally.

**Comment by AzukaChan** [comment]
Not having things saved locally is a good idea. I think its best to just stick with magnet links.
