### ISSUE TITLE
Wrong username or password

### ISSUE THREAD

**Issue by kirgizmustafa17** [KevinJDurant/OpenTorrentSite#15]
Hi, I deployed a Lamp Server in  **Google Cloud: Cloud Computing Services** and I did everything you wrote under **Setup**. But I can not create a new user with register page or phpmyadmin.  Actually, I created a new user in site register page but I can not upload any torrent and this created user is not showing up in phpmyadmin and if I logout and later try to login, I can not logging in. Error message is **Wrong username or password**

Can you show me how to create a user with phpmyadmin?
![image](https://user-images.githubusercontent.com/55243398/71319445-98d20980-24af-11ea-847e-d78e290943c0.png)

**Comment by AzukaChan** [comment]
Trying to manually enter a username and password in to the database won't work, you will need to make an account through the registration page.

Login to your phpmyadmin and navigate to your torrent database, select the users table and then select "structure" from the navigation bar at the top of the screen. From here you will need to set the default value of "uploaderstatus" to 0 instead of NULL which will most likely fix your issue.

**Comment by AzukaChan** [comment]
@kirgizmustafa17 Did this fix your issue?

**Comment by protocolprowler** [comment]
@AzukaChan Yes, this fixes the issue with new registrations not being saved to mySQL. Thank you. 
Updated user.sql script attached. 
[users.zip](https://github.com/KevinJDurant/OpenTorrentSite/files/4768021/users.zip)

**Comment by AzukaChan** [comment]
@bshuman Glad it worked for you.

@KevinJDurant this could probably be closed.
