### ISSUE TITLE
the user does not appear in the database

### ISSUE THREAD

**Issue by caetaniho** [KevinJDurant/OpenTorrentSite#23]
![user](https://user-images.githubusercontent.com/49878017/90323725-3bedfc80-df33-11ea-8c3e-77a8fa28bf7a.png)
when I register nothing appears in the phpmyadmin database "I'm using ubuntu server 18.04"

**Comment by AzukaChan** [comment]
@caetaniho 

Login to your phpmyadmin and navigate to your torrent database, select the users table and then select "structure" from the navigation bar at the top of the screen. From here you will need to set the default value of "uploaderstatus" to 0 instead of NULL which will most likely fix your issue.

You should also be using the "opentorrentsite.sql" file to install the database for now as this the most up to date version and some of the websites features may not work if you run the other 4 sql files individually.

**Comment by caetaniho** [comment]
I managed to solve the problem, it was in MYSQL I uninstalled it and installed MariaDB and it worked perfectly.

"a dirt on the torrent.php page could have a comment system, it would be a good"

**Comment by AzukaChan** [comment]
@caetaniho If you reinstalled the database using 'OpenTorrentSite.sql' that was likely what actually fixed your issue and not MariaDB, either way I'm glad it worked for you.

Yes a comment system would be nice and I do plan on adding one eventually, but I'm in no rush.
Feel free to create a fork and make one for yourself :3 maybe you could contribute to the project.

**Comment by AzukaChan** [comment]
@caetaniho comment system has been added, try re-pulling to check it out.
