### ISSUE TITLE
Torrent Contents Problem

### ISSUE THREAD

**Issue by alwisiax** [KevinJDurant/OpenTorrentSite#27]
Torrent file can contains only files not folders, if it contains a folder then it will be not be readable as object inside the upload function.

**Comment by AzukaChan** [comment]
I believe this is due to the changes you've made within the source code. Testing on my live webspace; all files and folders within the uploaded torrent appear in the filelist on the right hand side.

![newfolder](https://user-images.githubusercontent.com/42724187/98434328-57c00380-211a-11eb-92e0-5364cb47b206.PNG)

**Comment by alwisiax** [comment]
I will check thank you.
