### ISSUE TITLE
Torrents Not Uploading

### ISSUE THREAD

**Issue by theallegrarr** [KevinJDurant/OpenTorrentSite#6]
After uploading the torrent, it does not show up in list
but when i try to upload same torrent again
it says; "Sorry your file is already in use by another process, please try again later."

**Comment by AzukaChan** [comment]
1) Make sure you have set the appropriate file permissions on your web server.

2) Add a "torrents" folder to the root of your site.

3) If you want to be really thorough you can go into MySQL phpmyadmin and delete the torrent manually from the database, this should stop the issue from happening.

PS: I have a forked version of this torrent template that's a bit more up-to-date since the original uploader has stopped working on it.  You can check it out [here.](https://github.com/AzukaChan/OpenTorrentSite) This version allows you to login with your username as well as an updated torrent scraper. More actual features are on the way instead of just small changes.

Im currently using that fork to host my own torrent site at [torrents.azukachan.com](http://torrents.azukachan.com). Feel free to make an account and upload your torrents!
